# Generated by Django 2.0 on 2017-12-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_auto_20171220_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='cocktail',
            field=models.CharField(max_length=200),
        ),
    ]
