# Generated by Django 2.0 on 2017-12-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_auto_20171220_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
