# Generated by Django 2.0 on 2017-12-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_remove_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.Cocktail'),
        ),
    ]
