# Generated by Django 2.0 on 2017-12-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0008_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cocktail',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
